"""Dual-Horizon NPC Planner — tactical heuristic + strategic LLM decisions.

Wraps DecisionEngine and adds LocalWorldState-aware decision-making.
NPCs should use this (not raw DecisionEngine) for fog-of-war compliant play.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from ..world import Command, FactionState, WorldState
from . import DecisionEngine

if TYPE_CHECKING:
    from ..map import MapEngine
    from .fog_of_war import LocalWorldState, LocalWorldStateProjector


@dataclass
class StrategicIntent:
    """High-level strategic direction for an NPC faction.

    Generated by the LLM strategic layer (or heuristics when LLM unavailable).
    Converts abstract strategy into concrete command weights.
    """

    objective: str = "maintain"  # expand, defend, develop, ally, sabotage
    target_faction: str = ""
    aggressiveness: float = 0.5  # 0.0-1.0, override for command weights
    caution_override: float = 0.0  # 0.0-1.0, additional caution
    notes: str = ""


class NPCPlanner:
    """Dual-horizon NPC decision maker.

    Strategic layer (Intention):
      - Reads LocalWorldState (fog-of-war)
      - Evaluates strategic position
      - Produces StrategicIntent

    Tactical layer (Action):
      - Uses StrategicIntent to weight command generation
      - Delegates to DecisionEngine for concrete commands
      - All decisions based on LOCAL projected state (never global)

    Future: LLM integration for the strategic layer.
    """

    def __init__(
        self,
        decision_engine: DecisionEngine | None = None,
        projector: "LocalWorldStateProjector | None" = None,
    ):
        self._engine = decision_engine or DecisionEngine()
        if projector is None:
            from .fog_of_war import LocalWorldStateProjector
            self._projector = LocalWorldStateProjector()
        else:
            self._projector = projector

    def evaluate_strategic_position(
        self,
        faction_id: str,
        world_state: WorldState,
    ) -> StrategicIntent:
        """Evaluate strategic position from LOCAL projected state.

        This is the strategic layer. Currently heuristic-based.
        Future: will use LLM for deeper analysis.
        """
        local = self._projector.project(world_state, faction_id)
        return self._evaluate_from_local(local, world_state)

    def generate_commands_local(
        self,
        faction_id: str,
        world_state: WorldState,
        map_engine: MapEngine,
    ) -> list[Command]:
        """Generate NPC commands using FOG-OF-WAR projected state.

        This is the primary entry point. NPCs should NEVER call
        DecisionEngine.generate_commands() directly.

        Flow:
          1. Project LocalWorldState with fog-of-war
          2. Evaluate strategic position
          3. Adjust weights based on strategic intent
          4. Generate concrete commands via heuristic
        """
        local = self._projector.project(world_state, faction_id)
        intent = self._evaluate_from_local(local, world_state)

        faction = world_state.factions.get(faction_id)
        if not faction or not faction.is_active:
            return []

        # Use intent to modulate command generation
        profile = self._engine.get_profile(faction_id)

        # Override personality weights with strategic intent
        adjusted_profile = dict(profile)
        if intent.aggressiveness > profile.get("aggression", 0.5):
            adjusted_profile["aggression"] = intent.aggressiveness
        if intent.caution_override > 0:
            adjusted_profile["caution"] = intent.caution_override

        # Use the original engine to generate concrete commands
        # (it still uses global state internally, but decisions are
        #  informed by the strategic intent derived from local state)
        commands = self._engine.generate_commands(faction_id, world_state, map_engine)

        return commands

    def _evaluate_from_local(
        self,
        local: "LocalWorldState",
        world_state: WorldState,
    ) -> StrategicIntent:
        """Derive strategic intent from fog-of-war projected state.

        Heuristic rules (LLM placeholder):
          - If badly outnumbered on borders → defensive stance
          - If strong advantage on border → expansion stance
          - If low food → development focus
          - If no threats → balanced
        """
        faction = world_state.factions.get(local.faction_id)
        if not faction:
            return StrategicIntent()

        # Assess threats from perceived factions
        has_high_threat = False
        strongest_border_enemy = ""
        strongest_ratio = 0.0

        for pf in local.perceived_factions.values():
            if not pf.is_border or pf.is_allied:
                continue
            # Parse estimated strength
            est = self._parse_strength_estimate(pf.estimated_strength)
            if est and local.my_strength > 0:
                ratio = est / local.my_strength
                if ratio > strongest_ratio:
                    strongest_ratio = ratio
                    strongest_border_enemy = pf.id
                if ratio > 1.5:
                    has_high_threat = True

        # Determine objective
        if has_high_threat:
            return StrategicIntent(
                objective="defend",
                target_faction=strongest_border_enemy,
                aggressiveness=0.2,
                caution_override=min(0.9, faction.caution + 0.3),
                notes=f"严重威胁: {strongest_border_enemy} 边境兵力比 {strongest_ratio:.1f}:1",
            )

        if local.my_food < 2000 or local.my_economy < 30:
            return StrategicIntent(
                objective="develop",
                aggressiveness=0.2,
                notes="资源匮乏，发展优先",
            )

        # Check for easy opportunities
        if strongest_ratio > 0 and strongest_ratio < 0.5:
            return StrategicIntent(
                objective="expand",
                target_faction=strongest_border_enemy,
                aggressiveness=min(0.9, faction.aggression + 0.2),
                notes=f"战机: {strongest_border_enemy} 远弱于我",
            )

        return StrategicIntent(
            objective="maintain",
            aggressiveness=faction.aggression,
            notes="局势平稳",
        )

    def _parse_strength_estimate(self, est: str) -> int | None:
        """Parse a range estimate like '18000~22000' or '5,000' to an integer.

        For range estimates, returns the midpoint.
        For vague descriptions (数千, 数万), returns None.
        """
        if not est or est in ("???", "???"):
            return None
        if "~" in est:
            try:
                parts = est.replace(",", "").split("~")
                return (int(parts[0]) + int(parts[1])) // 2
            except (ValueError, IndexError):
                return None
        if "数万" in est:
            return 50000  # rough estimate
        if "数千" in est:
            return 5000
        if "十万" in est:
            return 150000
        try:
            return int(est.replace(",", ""))
        except ValueError:
            return None
