"""
三國志略 — CLI module with LLM GameMaster-driven gameplay.

Uses the LLM GameMaster for Plan/Command two-phase flow.
All advisor speeches, suggestions, consequences, and NPC actions
are generated by the LLM based on actual game state.

Falls back to offline_sim when no API key is available.
"""

from __future__ import annotations

import argparse
import contextlib

from rich import box
from rich.align import Align
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.prompt import Prompt
from rich.rule import Rule
from rich.table import Table
from rich.text import Text

from ..engine.game import GameEngine
from ..llm.adapter import LLMAdapter, detect_provider
from ..llm.game_master import GameMaster
from ..state.world_state import DATA_DIR, has_existing_game

console = Console()

ASCII_TITLE = r"""
       / \   |  _ \ / \  |_ _|_   _| \ | |_ _|  _ \
      / _ \  | |_) / _ \  | |  | | |  \| || || |_) |
     / ___ \ |  __/ ___ \ | |  | | | |\  || ||  _ <
    /_/   \_\_|_ /_/   \_\\___| |_| |_| \_|___|_| \_\
"""

TEMPERAMENT_STYLES = {
    "cautious":    ("\U0001f6e1", "blue"),
    "aggressive":  ("⚔", "red"),
    "scheming":    ("\U0001f575", "magenta"),
    "pragmatic":   ("\U0001f4cb", "green"),
    "strict":      ("\U0001f4dc", "yellow"),
    "proud":       ("\U0001f409", "bright_yellow"),
    "friendly":    ("\U0001f91d", "cyan"),
}


def run_game(force_new: bool = False):
    """Main game loop.

    Args:
        force_new: If True, ignore any existing save game
    """
    console.clear()
    _print_title()

    # --- Provider detection ---
    provider_info = detect_provider()
    llm = None
    game_master = None

    if provider_info["name"]:
        llm = LLMAdapter()
        game_master = GameMaster(llm)
        console.print(Panel(
            f"[bold green]✓ 检测到 {provider_info['name']} API[/] ({provider_info['model']})",
            border_style="green",
            title="\U0001f916 AI 游戏主持模式",
        ))
    else:
        console.print(Panel(
            "[bold yellow]⚠ 未检测到 API Key，将启动离线模式[/]\n\n"
            "离线模式基于事件驱动的规则引擎，有完整的战役/内政/外交体验。\n"
            "要体验 AI 生成的动态叙事，请设置环境变量：\n\n"
            "  export DEEPSEEK_API_KEY='sk-...'   # 推荐，价格低\n"
            "  export OPENAI_API_KEY='sk-...'     # OpenAI 兼容\n"
            "  export TONGYI_API_KEY='...'        # 通义千问\n",
            title="三國志略 · 离线模式",
            border_style="yellow",
        ))
        console.print("[dim]按回车开始...[/]")
        with contextlib.suppress(EOFError, KeyboardInterrupt):
            input()

    engine = GameEngine(llm=llm, new_game=force_new)

    # Check for existing save game
    if not force_new and has_existing_game():
        console.print(Panel(
            "[bold green]✓ 检测到历史存档，自动继续游戏[/]\n"
            f"[dim]使用 --new 可强制开始新游戏 | 删除 {DATA_DIR}/ 可重置所有数据[/]",
            border_style="green",
            title="\U0001f4c2 继续游戏",
        ))
        console.print("[dim]按回车继续...[/]")
        with contextlib.suppress(EOFError, KeyboardInterrupt):
            input()
        console.clear()
        _show_status_header(engine)
        _game_loop(engine, game_master)
        return

    # --- New Game: Faction Selection ---
    factions = [
        {"id": "cao", "name": "曹操军", "ruler": "曹操", "strength": 30000,
         "description": "乱世奸雄，奉天子以令不臣"},
        {"id": "shu", "name": "刘备军", "ruler": "刘备", "strength": 5000,
         "description": "汉室宗亲，以仁德取天下"},
        {"id": "wu", "name": "孙坚军", "ruler": "孙坚", "strength": 20000,
         "description": "江东猛虎，据长江天险"},
        {"id": "yuan_shao", "name": "袁绍军", "ruler": "袁绍", "strength": 80000,
         "description": "四世三公，讨董盟主"},
    ]

    console.print("\n[bold cyan]选择你的君主[/]\n")

    faction_table = Table(box=box.ROUNDED, border_style="cyan", header_style="bold cyan")
    faction_table.add_column("#", style="yellow", width=3)
    faction_table.add_column("势力", style="bold", width=15)
    faction_table.add_column("君主", width=12)
    faction_table.add_column("兵力", justify="right", width=10)
    faction_table.add_column("简介", width=35)

    for i, f in enumerate(factions, 1):
        faction_table.add_row(str(i), f["name"], f["ruler"],
                              f"{f['strength']:,}", f["description"])

    console.print(faction_table)
    console.print()

    choice = Prompt.ask("请选择",
                        choices=[str(i) for i in range(1, len(factions) + 1)],
                        default="1")
    selected = factions[int(choice) - 1]
    engine.set_player_faction(selected["id"])

    # --- Intro Scene ---
    console.clear()
    _show_status_header(engine, is_intro=True)

    with console.status("[yellow]天机运转，推演天下大势...[/]", spinner="dots"):
        intro = engine.get_intro_scene()

    _display_intro(engine, intro)
    _game_loop(engine, game_master)


def _game_loop(engine: GameEngine, game_master: GameMaster | None):
    """Main game loop with Plan/Command two-phase flow.

    LLM-driven when game_master is provided:
      Plan Mode  -> LLM generates advisor court + suggestions
      Player types free-text decision
      Command Mode -> LLM generates execution results + consequences

    Offline fallback when no game_master:
      Uses engine.process_turn() with offline_sim.
    """
    while True:
        # Check for elimination
        player = engine.world_state.get_player_faction()
        if not player or not player.is_active or player.strength <= 0:
            _display_game_over({
                "type": "defeat",
                "message": (
                    "# 势力覆灭\n\n"
                    "你的势力已经不复存在。\n"
                    "乱世之中，成王败寇。\n\n"
                    "感谢游玩《三國志略》。"
                ),
            })
            break

        # === PLAN MODE ===========================================
        if game_master:
            _display_llm_plan_mode(game_master, engine.world_state)
        else:
            _display_offline_plan_mode(engine)

        # === PLAYER DECISION =====================================
        console.print()
        decision = _get_player_decision()

        if decision is None:
            break
        if decision == "__plan__":
            continue
        if decision == "__state__":
            _display_state(engine)
            continue

        # === COMMAND MODE ========================================
        with console.status("[yellow]天机运转，推演天下大势...[/]", spinner="dots"):
            if game_master:
                result = game_master.generate_command_mode(
                    engine.world_state, decision
                )
                if "world_state" in result:
                    engine.world_state = result["world_state"]
                _display_llm_command_result(result)
            else:
                result = engine.process_turn(decision)
                _display_offline_command_result(engine, result)

            game_over = result.get("game_over")
            if game_over:
                _display_game_over(game_over)
                break


# ─── LLM Plan Mode Display ──────────────────────────────────

def _display_llm_plan_mode(gm: GameMaster, state):
    """Display LLM-generated Plan Mode: advisor court + suggestions."""
    with console.status("[yellow]谋臣正在商议国策...[/]", spinner="dots"):
        plan = gm.generate_plan_mode(state)

    # Season summary
    summary = plan.get("season_summary", "")
    if summary:
        console.print()
        console.print(Align(
            Text(summary, style="italic bright_cyan"),
            align="center",
        ))

    # Advisor court
    advisors = plan.get("advisors", [])
    if advisors:
        console.print()
        console.print(Rule("内政会议 — 谋臣献策", style="bright_magenta"))

        for adv in advisors:
            temperament = adv.get("temperament", "pragmatic")
            icon, color = TEMPERAMENT_STYLES.get(temperament, ("\U0001f4ac", "white"))
            name = adv.get("name", "谋臣")
            title = adv.get("title", "")
            speech = adv.get("speech", "")

            header = f"{icon} [bold {color}]{name}[/] [dim]({title})[/]"
            console.print(Panel(
                Text(speech, style="bright_white"),
                border_style=color,
                title=header,
                title_align="left",
                padding=(0, 1),
            ))

    # Suggestions
    suggestions = plan.get("suggestions", [])
    if suggestions:
        console.print()
        suggestion_grid = Table.grid(padding=(0, 2))
        for i, s in enumerate(suggestions, 1):
            suggestion_grid.add_row(
                f"[bold yellow]{i}.[/]",
                Text(str(s), style="bright_white"),
            )
        console.print(Panel(
            suggestion_grid,
            border_style="cyan",
            title="\U0001f3af 军师建议的方案",
            title_align="left",
        ))


# ─── LLM Command Mode Display ───────────────────────────────

def _display_llm_command_result(result: dict):
    """Display LLM Command Mode results with unified panels."""
    bureaucracy = result.get("bureaucracy", [])
    aftermath = result.get("aftermath", "")
    changes = result.get("state_changes", {})
    seeds = result.get("seeds", [])
    npc_reactions = result.get("npc_reactions", [])

    # 1. Bureaucracy execution report
    if bureaucracy:
        console.print()
        dept_parts = []
        for dept in bureaucracy:
            dept_name = dept.get("department", "")
            official = dept.get("official", "")
            action = dept.get("action", "")
            prefix = f"[{dept_name}"
            if official:
                prefix += f" · {official}"
            prefix += "]"
            dept_parts.append(f"[bold cyan]{prefix}[/] {action}")
        console.print(Panel(
            "\n\n".join(dept_parts),
            border_style="blue",
            title="\U0001f4dc 政令执行",
            title_align="left",
        ))

    # 2. Aftermath + state changes (merged into one panel)
    has_changes = changes and any(v for v in changes.values() if v)
    if aftermath or has_changes:
        parts = []
        if aftermath:
            parts.append(aftermath)
        if has_changes:
            if parts:
                parts.append("")
            labels = {
                "strength": "兵力", "economy": "经济", "morale": "民心",
                "treasury": "资金", "food": "粮草",
            }
            for key in sorted(changes):
                val = changes[key]
                if not val:
                    continue
                label = labels.get(key, key)
                sign = "+" if val > 0 else ""
                color = "green" if val > 0 else "red"
                parts.append(f"  [{color}]{label}: {sign}{val}[/]")

        console.print()
        console.print(Panel(
            "\n".join(parts),
            border_style="bright_yellow",
            title="⚡ 决策后果",
            title_align="left",
        ))

    # 3. Seeds (long-term)
    if seeds:
        console.print()
        seed_lines = []
        for s in seeds:
            trigger = s.get("trigger_after", "?")
            title = s.get("title", "未知")
            desc = s.get("description", "")
            seed_lines.append(
                f"[bold yellow]• {title}[/] [dim]({trigger}回合后)[/]\n"
                f"  [italic]{desc}[/]"
            )
        console.print(Panel(
            "\n".join(seed_lines),
            border_style="green",
            title="\U0001f331 潜在影响",
            title_align="left",
        ))

    # 4. NPC reactions
    if npc_reactions:
        console.print()
        console.print(Panel(
            "\n".join(f"  ⚔ {r}" for r in npc_reactions),
            border_style="yellow",
            title="\U0001f30d 天下动向",
            title_align="left",
        ))


# ─── Offline Fallback Displays ───────────────────────────────

def _display_offline_plan_mode(engine: GameEngine):
    """Minimal Plan Mode prompt for offline play."""
    player = engine.world_state.get_player_faction()
    if not player:
        return

    console.print()
    console.print(Panel(
        f"[bold]请下达你的战略决策[/]\n\n"
        f"兵力: [cyan]{player.strength:,}[/] | "
        f"经济: [green]{player.economy}/100[/] | "
        f"民心: [magenta]{player.morale}/100[/] | "
        f"资金: [yellow]{player.treasury:,}[/] | "
        f"粮草: [yellow]{player.food:,}[/]\n\n"
        "[dim]例如：发展内政、扩军备战、派遣使者联合袁绍、搜集敌方情报等[/]",
        border_style="bright_magenta",
        title="\U0001f3af 战略决策",
        title_align="left",
    ))


def _display_offline_command_result(engine: GameEngine, result: dict):
    """Display offline Command Mode results (offline_sim fallback)."""
    narrative_text = result.get("narrative", "")
    bureaucracy = result.get("bureaucracy", [])
    aftermath_text = result.get("aftermath", "")
    changes = result.get("state_changes", {})
    seeds = result.get("seeds", [])
    npc_actions = result.get("npc_actions", result.get("npc_reactions", []))
    events = result.get("events_occurred", [])
    choices = result.get("new_choices", [])

    # Narrative
    if narrative_text:
        console.print()
        console.print(Panel(
            narrative_text,
            border_style="green",
            title="\U0001f4dc 军师来报",
            title_align="left",
        ))

    # Bureaucracy
    if bureaucracy:
        dept_parts = []
        for dept in bureaucracy:
            dept_name = dept.get("department", "")
            official = dept.get("official", "")
            action = dept.get("action", "")
            prefix = f"[{dept_name}"
            if official:
                prefix += f" · {official}"
            prefix += "]"
            dept_parts.append(f"[bold cyan]{prefix}[/] {action}")
        if dept_parts:
            console.print()
            console.print(Panel(
                "\n\n".join(dept_parts),
                border_style="blue",
                title="\U0001f4dc 政令执行",
                title_align="left",
            ))

    # Aftermath + state changes merged
    player_changes = {
        k: v for k, v in changes.items()
        if k not in ("npc_changes", "before", "after") and v
    }
    if aftermath_text or player_changes:
        parts = []
        if aftermath_text:
            parts.append(aftermath_text)
        if player_changes:
            if parts:
                parts.append("")
            labels = {
                "strength": "兵力", "economy": "经济", "morale": "民心",
                "treasury": "资金", "food": "粮草",
            }
            for key in sorted(player_changes):
                val = player_changes[key]
                label = labels.get(key, key)
                sign = "+" if val > 0 else ""
                color = "green" if val > 0 else "red"
                parts.append(f"  [{color}]{label}: {sign}{val}[/]")

        console.print()
        console.print(Panel(
            "\n".join(parts),
            border_style="bright_yellow",
            title="⚡ 决策后果",
            title_align="left",
        ))

    # Seeds
    if seeds:
        console.print()
        seed_lines = []
        for s in seeds:
            desc = s.get("description", s.get("title", ""))
            seed_lines.append(f"[bold yellow]•[/] {desc}")
        console.print(Panel(
            "\n".join(seed_lines),
            border_style="green",
            title="\U0001f331 潜在影响",
            title_align="left",
        ))

    # NPC actions
    if npc_actions:
        console.print()
        console.print(Panel(
            "\n".join(f"  ⚔ {a}" for a in npc_actions),
            border_style="yellow",
            title="\U0001f30d 天下动向",
            title_align="left",
        ))

    # Events
    if events:
        console.print()
        console.print(Panel(
            "\n".join(f"  \U0001f4cc {e}" for e in events),
            border_style="red",
            title="⚡ 大事记",
            title_align="left",
        ))

    # Choices
    if choices and not result.get("game_over"):
        console.print()
        choice_grid = Table.grid(padding=(0, 2))
        for c in choices:
            num = c.split(".", 1)[0].strip() if "." in c else "?"
            text = c.split(".", 1)[1].strip() if "." in c else c
            choice_grid.add_row(f"[bold yellow]{num}.[/]", text)
        console.print(Panel(
            choice_grid,
            border_style="cyan",
            title="\U0001f3af 可选择的战略方向",
            title_align="left",
        ))


# ─── Intro Display ──────────────────────────────────────────

def _display_intro(engine: GameEngine, intro: dict):
    """Display the introductory scene."""
    narrative = intro.get("narrative", "")
    if narrative:
        console.print()
        console.print(Panel(
            Markdown(narrative),
            border_style="green",
            title="\U0001f4dc 序幕",
            title_align="left",
            padding=(1, 2),
        ))

    npc_actions = intro.get("npc_actions", [])
    if npc_actions:
        console.print()
        console.print(Panel(
            "\n".join(f"  ⚔ {a}" for a in npc_actions),
            border_style="yellow",
            title="\U0001f30d 天下大势",
            title_align="left",
        ))

    choices = intro.get("new_choices", [])
    if choices:
        console.print()
        choice_grid = Table.grid(padding=(0, 2))
        for c in choices:
            num = c.split(".", 1)[0].strip() if "." in c else "?"
            text = c.split(".", 1)[1].strip() if "." in c else c
            choice_grid.add_row(f"[bold yellow]{num}.[/]", text)
        console.print(Panel(
            choice_grid,
            border_style="cyan",
            title="\U0001f3af 开局选择",
            title_align="left",
        ))


# ─── Shared UI Components ────────────────────────────────────

def _show_status_header(engine: GameEngine, is_intro: bool = False):
    """Show a compact status header."""
    ws = engine.world_state
    player = ws.get_player_faction()
    if player:
        date_str = f"{ws.year}年·{_season_cn(ws.current_season)}"
        header = Panel(
            f"[bold yellow]{date_str}[/] | "
            f"兵力: [cyan]{player.strength:,}[/] | "
            f"经济: [green]{player.economy}/100[/] | "
            f"民心: [magenta]{player.morale}/100[/] | "
            f"资金: [yellow]{player.treasury:,}[/] | "
            f"粮草: [yellow]{player.food:,}[/]",
            border_style="bright_blue",
        )
        console.print(header)


def _get_player_decision() -> str | None:
    """Get player's free-text strategic decision.

    Returns:
        None for exit, "__plan__" to re-enter Plan Mode,
        "__state__" to view state, or the decision string.
    """
    console.print()
    console.print("[bold cyan]你的战略决策：[/]")
    console.print("[dim](自由输入 — 如同真实军师一般下达命令)[/]")
    console.print("[dim]  'plan' 重开内政会议 | 'state' 查看天下状态 | 'exit' 退出[/]")
    try:
        decision = Prompt.ask("").strip()
        if decision.lower() in ("exit", "quit", "退出", "q"):
            return None
        if decision.lower() in ("state", "状态"):
            return "__state__"
        if decision.lower() == "plan":
            return "__plan__"
        if not decision:
            return "__plan__"
        return decision
    except (EOFError, KeyboardInterrupt):
        return None


def _display_state(engine: GameEngine):
    """Show the current world state in detail."""
    ws = engine.world_state
    player = ws.get_player_faction()

    console.print()
    console.print(Panel(
        f"[bold yellow]{ws.year}年 {_season_cn(ws.current_season)}[/] | "
        f"第 {ws.turn} 回合",
        border_style="bright_blue",
        title="\U0001f30d 天下状态",
        title_align="left",
    ))

    if player:
        state_table = Table(box=box.SIMPLE, border_style="dim")
        state_table.add_column("属性", style="dim")
        state_table.add_column("数值", style="bold")
        state_table.add_row("势力", player.name)
        state_table.add_row("兵力", f"{player.strength:,}")
        state_table.add_row("经济", f"{player.economy}/100")
        state_table.add_row("民心", f"{player.morale}/100")
        state_table.add_row("资金", f"{player.treasury:,}")
        state_table.add_row("粮草", f"{player.food:,}")
        state_table.add_row("首都", player.capital or "—")
        state_table.add_row("领地", ", ".join(player.territories) if player.territories else "暂无")
        console.print(state_table)

    other_factions = [
        (fid, fs) for fid, fs in ws.factions.items()
        if fs.is_active and fid != ws.player_faction_id
    ]
    if other_factions:
        console.print()
        faction_table = Table(box=box.SIMPLE, border_style="dim")
        faction_table.add_column("势力", style="bold")
        faction_table.add_column("兵力", justify="right")
        faction_table.add_column("经济", justify="right")
        faction_table.add_column("民心", justify="right")
        for _fid, fs in other_factions[:8]:
            faction_table.add_row(
                fs.name, f"{fs.strength:,}",
                f"{fs.economy}", f"{fs.morale}",
            )
        console.print(faction_table)


def _print_title():
    """Print the game title ASCII art (once at startup)."""
    console.print(Panel(
        Align(Text(ASCII_TITLE, style="bold yellow"), align="center"),
        border_style="red",
        padding=1,
    ))
    console.print(Align(
        "[italic yellow]初平元年，汉室倾颓，群雄逐鹿。\n"
        "你将扮演一方诸侯，在这个风云激荡的时代书写你的传奇。[/]",
        align="center",
    ))


def _display_game_over(game_over: dict):
    """Display game over screen."""
    console.print()
    console.print(Panel(
        Markdown(game_over["message"]),
        border_style="bright_red" if game_over["type"] == "defeat" else "bright_green",
        title="\U0001f3c1 游戏结束",
        title_align="center",
        padding=2,
    ))
    console.print()


def _season_cn(season: str) -> str:
    mapping = {
        "spring": "春季", "summer": "夏季",
        "autumn": "秋季", "winter": "冬季",
    }
    return mapping.get(season, season)


def main():
    """Entry point with CLI argument parsing."""
    parser = argparse.ArgumentParser(
        description="三國志略 — AI 驱动的历史策略游戏",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--dev", action="store_true",
        help="启动开发模式（纯文本输入/输出，适合测试）",
    )
    parser.add_argument(
        "--new", action="store_true",
        help="强制开始新游戏（忽略存档）",
    )
    parser.add_argument(
        "--faction", type=int, choices=range(1, 5),
        help="直接选择势力编号（跳过选人界面，仅开发模式）",
    )

    args = parser.parse_args()

    if args.dev:
        from .dev_cli import run_dev
        run_dev(faction_choice=args.faction, force_new=args.new)
        return

    try:
        run_game(force_new=args.new)
    except KeyboardInterrupt:
        console.print("\n[yellow]退出游戏。[/]")
    except Exception as e:
        console.print(f"\n[red]游戏出错：{e}[/]")
        import traceback
        console.print(traceback.format_exc())
